# Generated by Django 3.2.9 on 2021-11-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20211121_0712'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='paygrade',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
